import '@cloudscape-design/global-styles/dark-mode-utils.css';
import '@cloudscape-design/global-styles/index.css';
import type { Metadata } from 'next';
import Navbar from './components/navigation/navbar';

export const metadata: Metadata = {
  title: 'Tom Smallwood',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body className={"class"}>
          <Navbar />
          {children}
        </body>
      </html>
    </>
  )
}
